# Default values for kubegres-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# global:

### Configuration for the kubegres contorller / operator
---
global:
  serviceAccountName: kubegres-controller-manager
  controlPlaneName: controller-manager
  # clusterName: 

replicas:
  controller: 3
  postgresql: 3

postgresql:
  image:
    registry: docker.io
    # repository: gcr.io/kubebuilder/kube-rbac-proxy
    # tag: v0.8.0
    repository: docker.io/postgres
    tag: 14.1
  port: 5432
  credentials: |
    superUserPassword: "postgresSuperUserPsw"
    replicationUserPassword: "postgresReplicaPsw"
    databaseName: "artifactory"
    databaseUserName: "postgres"
    databaseUserPassword: "password123"
  database:
    size: 20Mi
    storageClassName: standard
    volumeMount: /var/lib/postgresql/data
  resources:
    limits:
        memory: "40Mi"
        cpu: "10m"
    requests:
        memory: "20Mi"
        cpu: "10m"

  livenessProbe: |
    exec:
      command:
        - sh
        - -c
        - exec pg_isready -U postgres -h $POD_IP
    failureThreshold: 10
    initialDelaySeconds: 15
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 15
  readinessProbe: |
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3
  customConfiguration:
    secretName: mypostgres-conf
    postgresConf: |
      # Replication configs
      listen_addresses = '*'
      #  max_wal_senders = 10
      #  wal_keep_segments = 48 #in Mb
      max_connections = 2000
      #  shared_buffers = 128MB

      # Logging
      #  log_destination = 'stderr,csvlog'
      #  logging_collector = on
      #  log_directory = 'pg_log'
      #  log_filename= 'postgresql-%Y-%m-%d_%H%M%S.log'
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - uhn7kl4r3rbwk001.rmnkiba.local
            - uhn7kl4r3rbwk002.rmnkiba.local
            - uhn7kl4r3rbwk003.rmnkiba.local
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - mypostgres
              topologyKey: "kubernetes.io/hostname"



---


# helm install kubegres-test kubegres-chart/ --namespace kubegres-system
