---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresql.customConfiguration.secretName }}
data:
  postgres.conf: 
  {{ toYaml .Values.postgresql.customConfiguration.postgresConf | indent 2 }}
  # postgres.conf: |

  #   # Replication configs
  #   listen_addresses = '*'
  #   #  max_wal_senders = 10
  #   #  wal_keep_segments = 48 #in Mb
  #   max_connections = 2000
  #   #  shared_buffers = 128MB

  #   # Logging
  #   #  log_destination = 'stderr,csvlog'
  #   #  logging_collector = on
  #   #  log_directory = 'pg_log'
  #   #  log_filename= 'postgresql-%Y-%m-%d_%H%M%S.log'
---