apiVersion: v1
kind: Secret
metadata:
  name: mypostgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  superUserPassword: 'postgresSuperUserPsw'
  replicationUserPassword: 'postgresReplicaPsw'