apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubegres-leader-election-rolebinding
  namespace: kubegres-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubegres-leader-election-role
subjects:
- kind: ServiceAccount
  name: kubegres-controller-manager
  namespace: kubegres-system

