apiVersion: v2
name: kubegres-chart
description: A Helm chart for Kubegres
type: application
version: 0.1.0
appVersion: "1.15.0"
sources:
  - https://github.com/reactive-tech/kubegres
  - https://github.com/SarwarSaif/kubegres-helm-chart
maintainers:
  - name: Sarwar Saif
    email: saifmu6@gmail.com