# Default values for kubegres-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# global:

### Configuration for the kubegres contorller / operator
---
global:

replicas:
  controller: 3
  postgres: 3

proxy:
  image:
    registry: docker.io
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    tag: v0.8.0
  ports:
    containerPort: 8443

manager:
  image:
    registry: docker.io
    repository: reactivetechio/kubegres
    tag: 1.15
  resources:
    limits:
      cpu: "10m"
      memory: "20Mi"
    requests:
      cpu: "10m"
      memory: "20Mi"

postgres:
  image:
    registry: docker.io
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    tag: v0.8.0
---


# helm install kubegres-test kubegres-chart/ --namespace kubegres-system
